def get_config():
    return {
        'MODEL': {
            'NAME': 'cnn',
            'TAG': 'CNN',
            'NUM_CLASSES': 6,
            'DROP_PATH_RATE': 0.12,
            'LABEL_SMOOTHING': 0.05,
            'BASE_CHANNELS': 32,
            'DROPOUT': 0.45,
        },
        'DATA': {
            'DATA_PATH': None,
            'IMAGES_DIR': None,
            'METADATA_PATH': None,
            'CLEANED_METADATA_PATH': None,
            'IMAGE_COLUMN': None,
            'LABEL_COLUMN': None,
            'SPLIT_COLUMN': None,
            'VAL_SPLIT': None,
            'RETURN_METADATA': None,
            'BATCH_SIZE': None,
            'NUM_WORKERS': None,
            'PIN_MEMORY': None,
        },
        'TRAIN': {
            'START_EPOCH': None,
            'EPOCHS': 60,
            'BASE_LR': 3e-4,
            'WEIGHT_DECAY': 1e-3,
            'CLIP_GRAD': 1.0,
            'WARMUP_EPOCHS': 5,
            'WARMUP_LR': 1e-6,
            'MIN_LR': 1e-6,
            'OPT': 'adamw',
            'SCHED': 'cosine',
        },
        'OUTPUT': None,
    }
